type: DynamixelRobot
usb_port: /dev/tty.usbserial-FT1SF1UM
baud_rate: 57600
# baud_rate: 9600
# baud_rate: 3000000
motors: # use these same names as kwargs to constructors
- name: dxl_motor
  model: xl330-m288
  id: 1
  # operating_mode: 4
  operating_mode: 3
  # drive_mode: 8 # 8 will turn on torque_enable when position is commanded
  # drive_mode: 0 # 0 is default and will only move if torque is commanded
  velocity_limit: 2000
  goal_velocity: 1800
